In [162]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [163]:
df = pd.read_csv("online_retail.csv")

In [164]:
df.shape

(5711, 8)

In [165]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [166]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
5706,536874,22961,JAM MAKING SET PRINTED,1,12/3/2010 11:35,1.45,16891.0,United Kingdom
5707,536874,22144,CHRISTMAS CRAFT LITTLE FRIENDS,1,12/3/2010 11:35,2.10,16891.0,United Kingdom
5708,536874,82483,WOOD 2 DRAWER CABINET WHITE FINISH,2,12/3/2010 11:35,5.95,16891.0,United Kingdom
5709,536874,22702,BLACK AND WHITE CAT BOWL,1,12/3/2010 11:35,2.10,16891.0,United Kingdom
5710,536874,21462,"NURSERY A,B,C PAINTED LETTERS",1,12/3/2010 11:35,6.75,16891.0,United Kingdom

In [167]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5711 entries, 0 to 5710
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    5711 non-null   str
 1   StockCode    5711 non-null   str
 2   Description  5699 non-null   str
 3   Quantity     5711 non-null   int64
 4   InvoiceDate  5711 non-null   str
 5   UnitPrice    5711 non-null   float64
 6   CustomerID   4237 non-null   float64
 7   Country      5711 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 357.1 KB

In [168]:
df.describe()

          Quantity    UnitPrice    CustomerID
count  5711.000000  5711.000000   4237.000000
mean      8.788128     4.077270  15855.829832
std     135.750251    14.582375   1758.250202
min   -9360.000000     0.000000  12427.000000
25%       1.000000     1.250000  14573.000000
50%       3.000000     2.510000  15862.000000
75%      10.000000     4.250000  17841.000000
max    2880.000000   607.490000  18239.000000

In [169]:
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [170]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [171]:
df["StockCode"].nunique()

1670

In [172]:
df["Country"].unique()

<StringArray>
['United Kingdom',         'France',      'Australia',    'Netherlands',
        'Germany',         'Norway',           'EIRE',    'Switzerland']
Length: 8, dtype: str

In [173]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description      12
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     1474
Country           0
dtype: int64

In [174]:
df[df["CustomerID"].isnull()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,12/1/2010 14:32,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,12/1/2010 14:32,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,12/1/2010 14:32,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,12/1/2010 14:32,1.66,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
5682,536865,85152,HAND OVER THE CHOCOLATE SIGN,1,12/3/2010 11:28,4.21,NaN,United Kingdom
5683,536865,85176,SEWING SUSAN 21 NEEDLE SET,1,12/3/2010 11:28,1.66,NaN,United Kingdom
5684,536865,M,Manual,1,12/3/2010 11:28,2.55,NaN,United Kingdom
5685,536865,DOT,DOTCOM POSTAGE,1,12/3/2010 11:28,498.47,NaN,United Kingdom
5686,536866,72803b,OCEAN SCENT CANDLE JEWELLED DRAWER,1,12/3/2010 11:28,8.47,NaN,United Kingdom

In [175]:
df.duplicated().sum()

np.int64(92)

In [176]:
df = df.drop_duplicates()

In [177]:
df.shape

(5619, 8)

In [178]:
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [179]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [180]:
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [181]:
df[df["Quantity"] < 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
5259,C536853,84678,CLASSICAL ROSE SMALL VASE,-1,2010-12-03 10:07:00,2.55,14679.0,United Kingdom
5260,C536854,22158,3 HEARTS HANGING DECORATION RUSTIC,-1,2010-12-03 10:09:00,2.95,15240.0,United Kingdom
5261,C536854,22944,CHRISTMAS METAL POSTCARD WITH BELLS,-1,2010-12-03 10:09:00,1.25,15240.0,United Kingdom
5262,C536854,21871,SAVE THE PLANET MUG,-1,2010-12-03 10:09:00,1.25,15240.0,United Kingdom
5263,C536855,21527,RED RETROSPOT TRADITIONAL TEAPOT,-4,2010-12-03 10:11:00,7.95,18225.0,United Kingdom

In [182]:
df[df["UnitPrice"] <= 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom

In [183]:
df[df["Quantity"] < 0].shape

(82, 8)

In [184]:
df = df[df["Quantity"] >= 0]

In [185]:
df.shape

(5537, 8)

In [186]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description      10
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     1472
Country           0
dtype: int64

In [187]:
df["Description"] = df["Description"].fillna("Unknown")

In [188]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description       0
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     1472
Country           0
dtype: int64

In [189]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [190]:
(df["Quantity"] < 0).sum()

np.int64(0)

In [191]:
df["CustomerID"] = df["CustomerID"].astype("Int64")

In [192]:
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID              Int64
Country                   str
dtype: object

In [193]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [194]:
df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["Day"] = df["InvoiceDate"].dt.day
df["Hour"] = df["InvoiceDate"].dt.hour
df["DayName"] = df["InvoiceDate"].dt.day_name()

In [195]:
df["IsReturn"] = df["Quantity"] < 0

In [196]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Revenue', 'Year', 'Month', 'Day',
       'Hour', 'DayName', 'IsReturn'],
      dtype='str')

In [197]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,Day,Hour,DayName,IsReturn
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,1,8,Wednesday,False
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,False
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,1,8,Wednesday,False
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,False
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,False

In [198]:
# Total Revenue
df["Revenue"].sum()

np.float64(115615.8)

In [199]:
# Average order value
order_revenue = df.groupby("InvoiceNo")["Revenue"].sum()
aov = order_revenue.mean()

In [200]:
aov

np.float64(390.5939189189189)

In [201]:
order_revenue

InvoiceNo
536365     139.12
536366      22.20
536367     278.73
536368      70.05
536369      17.85
           ...
536863     112.27
536864     636.68
536865    2396.96
536866       8.47
536874      78.01
Name: Revenue, Length: 296, dtype: float64

In [202]:
# Number of Invoice No.
df["InvoiceNo"].count()

np.int64(5537)

In [203]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description       0
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     1472
Country           0
Revenue           0
Year              0
Month             0
Day               0
Hour              0
DayName           0
IsReturn          0
dtype: int64

In [204]:
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID              Int64
Country                   str
Revenue               float64
Year                    int32
Month                   int32
Day                     int32
Hour                    int32
DayName                   str
IsReturn                 bool
dtype: object

In [205]:
df["UnitPrice"] = df["UnitPrice"].astype(int)

In [206]:
sales_df = df[df["IsReturn"] == False]

In [207]:
sales_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,Day,Hour,DayName,IsReturn
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2,17850,United Kingdom,15.30,2010,12,1,8,Wednesday,False
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,False
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2,17850,United Kingdom,22.00,2010,12,1,8,Wednesday,False
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,False
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5706,536874,22961,JAM MAKING SET PRINTED,1,2010-12-03 11:35:00,1,16891,United Kingdom,1.45,2010,12,3,11,Friday,False
5707,536874,22144,CHRISTMAS CRAFT LITTLE FRIENDS,1,2010-12-03 11:35:00,2,16891,United Kingdom,2.10,2010,12,3,11,Friday,False
5708,536874,82483,WOOD 2 DRAWER CABINET WHITE FINISH,2,2010-12-03 11:35:00,5,16891,United Kingdom,11.90,2010,12,3,11,Friday,False
5709,536874,22702,BLACK AND WHITE CAT BOWL,1,2010-12-03 11:35:00,2,16891,United Kingdom,2.10,2010,12,3,11,Friday,False
5710,536874,21462,"NURSERY A,B,C PAINTED LETTERS",1,2010-12-03 11:35:00,6,16891,United Kingdom,6.75,2010,12,3,11,Friday,False

In [208]:
sales_df.shape

(5537, 15)

In [213]:
# unique invoices
df["InvoiceNo"].nunique()

296

In [214]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Revenue', 'Year', 'Month', 'Day',
       'Hour', 'DayName', 'IsReturn'],
      dtype='str')

In [215]:
# unique products sold
df["StockCode"].nunique()

1660

In [216]:
# unique customers
df['CustomerID'].nunique()

200

In [ ]:
# total units sold
sales_df["Quantity"].sum()

np.int64(60785)

In [ ]:
# Average quantity per order
df.groupby("InvoiceNo")["Quantity"].mean()

InvoiceNo
536365    5.714286
536366    6.000000
536367    6.916667
536368    3.750000
536369    3.000000
            ...
536863    1.738095
536864    1.404255
536865    2.264286
536866    1.000000
536874    1.478261
Name: Quantity, Length: 296, dtype: float64

In [ ]:
# Average unitprice
df["UnitPrice"].mean()

np.float64(3.5295286256095357)

In [ ]:
# Largest order by revenue
df["Revenue"].max()

np.float64(1627.2)

In [229]:
# 10 products have highest quantity sold
top_10_products = (
    sales_df.groupby(["StockCode", "Description"])["Quantity"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(top_10_products)

StockCode  Description
84077      WORLD WAR 2 GLIDERS ASSTD DESIGNS     3312
84950      ASSORTED COLOUR T-LIGHT HOLDER        1842
21915      RED  HARMONICA IN BOX                 1549
85123A     WHITE HANGING HEART T-LIGHT HOLDER     769
84879      ASSORTED COLOUR BIRD ORNAMENT          727
21212      PACK OF 72 RETROSPOT CAKE CASES        700
84029E     RED WOOLLY HOTTIE WHITE HEART.         686
22616      PACK OF 12 LONDON TISSUES              656
21232      STRAWBERRY CERAMIC TRINKET BOX         617
21137      BLACK RECORD COVER FRAME               613
Name: Quantity, dtype: int64